version: '3'
services:
  serversugar27:
    container_name: myserversugar27
    build: ./server3
    ports:
      - '3003:3003'
    environment:
      - MONGO_URI=mongodb://mongosugar27:27019/vrpsugar27
      - AUTH_MONGO_URI=mongodb://mongo_vrpjob:27017/vrpjob
      - PORT=3003
      - JWT_SECRET=jwtSecret
      - CONFIRM_PASSWORD=vrp27sugar
    volumes:
      - ./server3/spupload:/usr/src/app/spupload
      - ./server3/controllers:/usr/src/app/controllers
      - ./server3/routes:/usr/src/app/routes
      - ./server3/data/backupData:/usr/src/app/data/backupData
      - ./server3/data/initData:/usr/src/app/data/initData
      - ./server3/data/restoreData:/usr/src/app/data/restoreData
    links:
      - mongosugar27
  mongosugar27:
    container_name: mymongosugar27
    command: mongod --port 27019
    image: mongo
    ports:
      - '27019:27019'
    volumes:
      - ./mongo3/mydb:/data/db

networks: 
  default: 
    external: 
      name: external-network-vrpjob